services:
  neo4j:
    image: neo4j:5.5.0
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/fadwa1234
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - neo4j-data:/data
    networks:
      - crud-network

  crud-api:
    image: crud-api-image
    build:
      context: .
    ports:
      - "8081:8080"  # Change ici le port externe (hôte) de 8080 à 8081
    depends_on:
      - neo4j
    networks:
      - crud-network

networks:
  crud-network:
    driver: bridge

volumes:
  neo4j-data:
    driver: local
